### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by maximehery** [VaughnValle/elektropunk#1]
Some files are missing like the scripts to launch poybar for example (launch.sh, dunst.sh, bspswallow.sh, launchlistener.sh, colors.sh), the config of some packages too, it seems to me.

**Comment by VaughnValle** [comment]
My bad. I forgot to include the scripts directory in the repo. I just pushed a commit and the scripts directory should be there now. Can you copy everything to a folder (preferably to ~/.config/scripts) and see if it successfully locates the missing scripts?

**Comment by VaughnValle** [comment]
Any update?

**Comment by maximehery** [comment]
> Any update?

I switched to another environment under Awesome, but otherwise overall everything was working pretty well :smile:

**Comment by VaughnValle** [comment]
That's great! Keen to try out AwesomeWM soon :) Closing this issue now
