### ISSUE TITLE
rofi-fb.sh,calc files from scripts missing

### ISSUE THREAD

**Issue by neel2468** [VaughnValle/elektropunk#5]

**Comment by VaughnValle** [comment]
Hi! Sorry for the really late reply. I added the rofi-fb.sh file in the latest commit https://github.com/VaughnValle/elektropunk/commit/7a5fdac109b1995c274dd76e46e24fc01c8ca9df under the elektropunk/scripts directory. Please let me know for any further errors :) Cheers

**Comment by VaughnValle** [comment]
Closed for inactivity
